apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-webapp

resources:
- namespace.yaml
- crd.yaml
- custom-resource.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
