apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- deployment.yaml
- service.yaml

configMapGenerator:
- name: nginx-config
  literals:
  - environment=base
  - log_level=info

labels:
- pairs:
    app: nginx
